"""27_04_2023_autoincrement

Revision ID: 1725fb8642fd
Revises: 95acde6273b7
Create Date: 2023-04-27 12:54:28.232532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1725fb8642fd'
down_revision = '95acde6273b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
